### ISSUE TITLE
透明背景gif保存后变成黑色背景

### ISSUE THREAD

**Issue by chocking** [STDSuperman/super-image-cropper#1]
源码位置：https://github.com/STDSuperman/super-image-cropper/blob/5fbcf76c14ae0fa52dfdaa1db2880fa7266361a9/src/lib/synthetic-gif.ts#L28

参考 https://github.com/jnordberg/gif.js 文档，是否可以暴露```transparent```参数乃至其他gif参数到外面？

**Comment by STDSuperman** [comment]
可以的，我支持一下

**Comment by STDSuperman** [comment]
你如果想设置 gif 最终产出的背景颜色的话只要设置 cropperJsOpts 参数中的 background 即可，不过 gifjs 的参数我也可以暴露给你，但是我看好像那个参数对这个没啥正向影响；这个透明色好像支持的也有点小问题，我看看怎么解决下。

**Comment by chocking** [comment]
https://github.com/fengyuanchen/cropperjs#background cropperJs的background不是设置网格的么

**Comment by STDSuperman** [comment]
> https://github.com/fengyuanchen/cropperjs#background cropperJs的background不是设置网格的么

你传给我的这个 background 我会在对 gif 每一帧进行裁切的时候，fillStyle 到背景里去，这个 background 和 cropperjs 里的 background 不是一个用途。

**Comment by chocking** [comment]
> 你如果想设置 gif 最终产出的背景颜色的话只要设置 cropperJsOpts 参数中的 background 即可，不过 gifjs 的参数我也可以暴露给你，但是我看好像那个参数对这个没啥正向影响；这个透明色好像支持的也有点小问题，我看看怎么解决下。

好的，确实其他颜色可以，透明不行

**Comment by STDSuperman** [comment]
还发现透明 gif 最终结果会有重影，这个我已经修复了，跟着 gif 透明背景这个一起发一版

**Comment by STDSuperman** [comment]
@chocking 相关问题已全部修复并支持，最新版本 1.0.7
