### ISSUE TITLE
Not returning a valid blob for gif images with react-cropper.

### ISSUE THREAD

**Issue by Shanky1001** [STDSuperman/super-image-cropper#10]
The package is not returning a valid blob type in case of gif image due to which it can't be converted into base64 encoding and thus it's impossible to send and manipulate the image on later stages.

**Comment by STDSuperman** [comment]
> The package is not returning a valid blob type in case of gif image due to which it can't be converted into base64 encoding and thus it's impossible to send and manipulate the image on later stages.

Thank you for the issue. Can you give a reproducible case?

**Comment by Shanky1001** [comment]
Yeah, in case you want to convert that into base64 to send it on server, it fails. It says not a valid type of blob.

**Comment by STDSuperman** [comment]
> Yeah, in case you want to convert that into base64 to send it on server, it fails. It says not a valid type of blob.

Let me test it.

**Comment by Shanky1001** [comment]
> > Yeah, in case you want to convert that into base64 to send it on server, it fails. It says not a valid type of blob.
> 
> Let me test it.

Sure.

**Comment by STDSuperman** [comment]
```ts
superImageCropperInstance?.crop({
   cropperInstance: cropperInstanceRef.current,
   src: sourceImage
}).then((blobUrl: string) => {    
   // blob url to base64
   const xhr = new XMLHttpRequest();
   xhr.onload = function() {
      const reader = new FileReader();
      reader.onloadend = function() {
          console.log(reader.result);
      }
      reader.readAsDataURL(xhr.response);
   };
   xhr.open('GET', blobUrl);
   xhr.responseType = 'blob';
      xhr.send();
   });
```

Maybe you're converting to base64 the wrong way. @shanky-ced.

**Comment by STDSuperman** [comment]
The default output parameter is not a blob, but a blob URL. I'll consider adding a parameter to set the output type.

**Comment by Shanky1001** [comment]
> ```ts
> superImageCropperInstance?.crop({
>    cropperInstance: cropperInstanceRef.current,
>    src: sourceImage
> }).then((blobUrl: string) => {    
>    // blob url to base64
>    const xhr = new XMLHttpRequest();
>    xhr.onload = function() {
>       const reader = new FileReader();
>       reader.onloadend = function() {
>           console.log(reader.result);
>       }
>       reader.readAsDataURL(xhr.response);
>    };
>    xhr.open('GET', blobUrl);
>    xhr.responseType = 'blob';
>       xhr.send();
>    });
> ```
> 
> Maybe you're converting to base64 the wrong way. @shanky-ced.

if this code works then yeah, because i was trying directly with FileReader to convert it.

**Comment by STDSuperman** [comment]
> > ```ts
> > superImageCropperInstance?.crop({
> >    cropperInstance: cropperInstanceRef.current,
> >    src: sourceImage
> > }).then((blobUrl: string) => {    
> >    // blob url to base64
> >    const xhr = new XMLHttpRequest();
> >    xhr.onload = function() {
> >       const reader = new FileReader();
> >       reader.onloadend = function() {
> >           console.log(reader.result);
> >       }
> >       reader.readAsDataURL(xhr.response);
> >    };
> >    xhr.open('GET', blobUrl);
> >    xhr.responseType = 'blob';
> >       xhr.send();
> >    });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe you're converting to base64 the wrong way. @shanky-ced.
> 
> if this code works then yeah, because i was trying directly with FileReader to convert it.

![image](https://user-images.githubusercontent.com/44311619/212459791-977a8362-16be-4be6-a29e-8bd79319bb5d.png)

**Comment by Shanky1001** [comment]
@STDSuperman thank you for the screenshot, i was going to try it out too.

**Comment by STDSuperman** [comment]
@shanky-ced You can set the output type in version 1.0.15.

**Comment by STDSuperman** [comment]
e.g

```ts
superImageCropperInstance?.crop({
   cropperInstance: cropperInstanceRef.current,
   src: sourceImage,
   outputType: 'base64'
})
```

**Comment by Shanky1001** [comment]
> @shanky-ced You can set the output type in version 1.0.15.

woah, that's great, thank you for helping out. @STDSuperman

**Comment by STDSuperman** [comment]
> > @shanky-ced You can set the output type in version 1.0.15.
> 
> woah, that's great, thank you for helping out. @STDSuperman

If this version solves your problem, then you're ready to close the issue.

**Comment by Shanky1001** [comment]
> > > @shanky-ced You can set the output type in version 1.0.15.
> > 
> > 
> > woah, that's great, thank you for helping out. @STDSuperman
> 
> If this version solves your problem, then you're ready to close the issue.

Yeah, It's working for me, Thanks.
