### ISSUE TITLE
error in some gif images on cropping

### ISSUE THREAD

**Issue by Shanky1001** [STDSuperman/super-image-cropper#13]
This error occurs on some gif images during cropping.
I tried to resolve this issue locally and found the issue happening only in some particular frames of image. try catch works in most cases and it skip that frame.

```
 RangeError: offset is out of bounds
    at Uint8ClampedArray.set (<anonymous>)
```

**Comment by STDSuperman** [comment]
Whether skipping some frames will affect the final effect?

**Comment by STDSuperman** [comment]
Please give me some reproducible pictures.

**Comment by Shanky1001** [comment]
> Whether skipping some frames will affect the final effect?

Skipping frames didn't affected those images in my case. i tried try catch method in your code and it successfully skipped those frames without affecting a lot.

**Comment by Shanky1001** [comment]
> Please give me some reproducible pictures.

try Images in this repo.
[repo link]( https://github.com/shanky-ced/StockWatchlist)

**Comment by STDSuperman** [comment]
> > Please give me some reproducible pictures.
> 
> try Images in this repo. [repo link](https://github.com/shanky-ced/StockWatchlist)

Let me see.

**Comment by STDSuperman** [comment]
This problem will be solved by this pr(#14).

**Comment by STDSuperman** [comment]
`v1.0.16` has been released.

**Comment by Shanky1001** [comment]
> `v1.0.16` has been released.

Thanks, its working perfectly fine. @STDSuperman

**Comment by Shanky1001** [comment]
> `v1.0.16` has been released.

Buddy, this change is creating more issue. it is now distorting gif images. for reference check the [repo](https://github.com/shanky-ced/StockWatchlistl) images again. u can try this image  [trollge-we-do-a-little-trolling.gif](https://github.com/shanky-ced/StockWatchlist/blob/main/trollge-we-do-a-little-trolling.gif) or [5eeea355389655.59822ff824b72.gif](https://github.com/shanky-ced/StockWatchlist/blob/main/5eeea355389655.59822ff824b72.gif)

**Comment by STDSuperman** [comment]
Let me see!

**Comment by STDSuperman** [comment]
I found the problem. I'll fix it.

**Comment by shanky-ced** [comment]
> I found the problem. I'll fix it.

okay.

**Comment by Shanky1001** [comment]
> I found the problem. I'll fix it.

Okay

**Comment by STDSuperman** [comment]
`super-image-cropper@1.0.17` fixed this issue.

**Comment by Shanky1001** [comment]
> `super-image-cropper@1.0.17` fixed this issue.

great, thanks for fixing buddy.
