### ISSUE TITLE
problem with rotate in cropperJsOpts

### ISSUE THREAD

**Issue by hamza3e** [STDSuperman/super-image-cropper#16]
There is a problem with rotate parameter if it is bigger than 45 or smaller than 0

**Comment by STDSuperman** [comment]
Can you give a more detailed description of this problem?

**Comment by STDSuperman** [comment]
Let me have a try.

**Comment by STDSuperman** [comment]
I will fix this issue in the coming days. Thank you for your feedback.

**Comment by STDSuperman** [comment]
I have released a beta to fix this issue. Try it with version `1.0.18-beta.1`.

**Comment by STDSuperman** [comment]
Sorry it took so long to fix it.
