### ISSUE TITLE
打包有问题

### ISSUE THREAD

**Issue by zliang01** [STDSuperman/super-image-cropper#18]
哈喽，使用这个之后，使用rollup打包成js时，gift的构造函数会丢失。
![9240487550a26ef5ba468f2fbd2bd92](https://github.com/STDSuperman/super-image-cropper/assets/15192404/a8283259-6c15-4d3c-9f8f-899ae2254cd6)
![af14c7ac3893b17cb32b4f871a8a017](https://github.com/STDSuperman/super-image-cropper/assets/15192404/856a5836-c62b-4040-9673-aada30802015)

**Comment by zliang01** [comment]
import GIF from gif.js';  修改为  const GIF = require('gif.js');  就好了

**Comment by zliang01** [comment]
done

**Comment by STDSuperman** [comment]
感觉是不是你在编译时处理 cjs module 有点小问题呢，理论上给 ts 项目开启了allowSyntheticDefaultImports 一般编译的的产物都会兼容的

**Comment by STDSuperman** [comment]
没其他问题准备关单了哦

**Comment by zliang01** [comment]
百度的amis，使用rollup打包，看了下配置都是开了的，只有修改上面的内容才能正常生成构造函数。
![image](https://github.com/STDSuperman/super-image-cropper/assets/15192404/66478bc0-dede-4e88-ab61-6e104c1d7b8d)

**Comment by STDSuperman** [comment]
似乎你的问题是打包 amis 项目有问题，不是我的这个项目是么

**Comment by STDSuperman** [comment]
方便的话可以把你的 rollup 配置发出来我看看

**Comment by zliang01** [comment]
![image](https://github.com/STDSuperman/super-image-cropper/assets/15192404/afc50bea-8269-458b-b6cb-060ea4e517cb)
fa方便的话可以进群，看下

**Comment by STDSuperman** [comment]
看着似乎不是我这个项目的打包问题吧[😂](https://emojipedia.org/face-with-tears-of-joy)

**Comment by zliang01** [comment]
我已经说的很清楚了。import GIF from gif.js'; 修改为 const GIF = require('gif.js'); 就好了 你这个引入的方式不规范造成的

**Comment by zliang01** [comment]
你觉得没问题就没问题吧

**Comment by STDSuperman** [comment]
> 我已经说的很清楚了。import GIF from gif.js'; 修改为 const GIF = require('gif.js'); 就好了 你这个引入的方式不规范造成的

哥，我看你截图上不是 amis 这个项目的问题么，跟我这个包有啥关系...
