### ISSUE TITLE
裁剪设置的偏移没有效果， 或不准确

### ISSUE THREAD

**Issue by jinjiebang** [STDSuperman/super-image-cropper#21]
- 如果使用left和top, 没有效果
- 如果使用x和y, 位置不对

`          imageCropper.crop({
            src: imageRef.currentSrc,
            cropperJsOpts: {
              width: scaledCropWidth,
              height: scaledCropHeight,
              x: scaledCropX,
              y: scaledCropY,
            },
            outputType: 'blob',
          }).then(res => resolve(res as Blob));
`
使用最新版本1.0.20
这是截的中间
![联想截图_20240926165915](https://github.com/user-attachments/assets/5c81d495-e16b-4b89-8602-9771c251736a)
结果是
![联想截图_20240926165932](https://github.com/user-attachments/assets/7235ae04-5cc2-4211-a899-f9170a286536)
已查看日志，没有缩放影响，x, y传入的也是对的

**Comment by STDSuperman** [comment]
我晚点看看

**Comment by jinjiebang** [comment]
![image](https://github.com/user-attachments/assets/cfefa69f-d059-4ec1-8968-ba29ee061013)
这块代码看不太懂， 是否计算错误

**Comment by jinjiebang** [comment]
这是我使用的图片
![Wow-gif](https://github.com/user-attachments/assets/c1ae6c85-336a-44e1-b3be-cda854ed4c9a)
是配合    "react-easy-crop": "^5.0.8",  使用的，看日志，截图区域没问题

**Comment by STDSuperman** [comment]
我看了下没问题的，估计你的 x, y 有点问题吧
![image](https://github.com/user-attachments/assets/64d32b51-4f39-4846-b446-835d83cbc8e8)

**Comment by STDSuperman** [comment]
哦好像cropperJs 返回的 left 和 top 有点奇怪，我这里之前主要适配的 cropperJs 场景，我调一下

**Comment by STDSuperman** [comment]
bug 已修复，可以用这个版本验证一下，没问题的话我发个正式版：super-image-cropper@1.0.21-beta.0

**Comment by jinjiebang** [comment]
太给力了，我明天试下

**Comment by jinjiebang** [comment]
> bug 已修复，可以用这个版本验证一下，没问题的话我发个正式版：super-image-cropper@1.0.21-beta.0

已验证修复
