### ISSUE TITLE
Transparancy with each frame

### ISSUE THREAD

**Issue by mcerejo** [STDSuperman/super-image-cropper#7]
When cropping a gif (the one from the example), there is a problem with each frame that is cropped, it looses color! This could be related to the https://github.com/jnordberg/gif.js component, or by some config, but this should be a major bug on this module.
![d10b83ac](https://user-images.githubusercontent.com/110612277/187513849-73569ef9-eb72-4eea-8ebe-770d9165eb2e.gif)

**Comment by STDSuperman** [comment]
Let me see!

**Comment by STDSuperman** [comment]
There seems to be a problem with the GIF parsing library that [gifuct-js](https://github.com/matt-way/gifuct-js) relies on.

**Comment by mcerejo** [comment]
Is this issue fixable in this package, or can we "throw" this issue? it looks like its something related to this issue https://github.com/matt-way/gifuct-js/issues/29. Maybe @jeetiss could help with some integration?

**Comment by STDSuperman** [comment]
> Is this issue fixable in this package, or can we "throw" this issue? it looks like its something related to this issue [matt-way/gifuct-js#29](https://github.com/matt-way/gifuct-js/issues/29). Maybe @jeetiss could help with some integration?

It might solve my problem. I'll look into it.

**Comment by STDSuperman** [comment]
> Is this issue fixable in this package, or can we "throw" this issue? it looks like its something related to this issue [matt-way/gifuct-js#29](https://github.com/matt-way/gifuct-js/issues/29). Maybe @jeetiss could help with some integration?

My branch [fix/color-loose](https://github.com/STDSuperman/super-image-cropper/tree/fix/color-loose) will solve this problem.

**Comment by STDSuperman** [comment]
> Is this issue fixable in this package, or can we "throw" this issue? it looks like its something related to this issue [matt-way/gifuct-js#29](https://github.com/matt-way/gifuct-js/issues/29). Maybe @jeetiss could help with some integration?

Thanks for the tip.

**Comment by STDSuperman** [comment]
This problem has been fixed. But there is still a small bug with `gif.js`.If you pass the transparent parameter to `gif.js` (A built-in behavior). You will get the following effect.
<img src="https://user-images.githubusercontent.com/44311619/193037082-4b28f8c9-97c8-49c3-942a-e4ae101ae0f2.png" width="300"/>

If you need to fix this problem. You need to reset the configuration. Like this:

```ts
superImageCropperInstance?.crop({
 gifJsOptions: {
   transparent: null
 }
})
```
And then you can see the effect:
<img src="https://user-images.githubusercontent.com/44311619/193038435-db8b8c22-07f8-468c-a7bf-5f7666ec14e5.png" width="300"/>

**Comment by DesignTHN** [comment]
@STDSuperman is there a way to keep the transparency for gifs without background, but also solve this issue with 
```
 gifJsOptions: {
   transparent: null
 }
```
??
